### ISSUE TITLE
Script make cache-warmup returned with error code 2

### ISSUE THREAD

**Issue by Jackson8Zhang** [symfony/skeleton#17]
- Configuring symfony/twig-bundle (3.3): From github.com/symfony/recipes:master
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  cannot warmup the cache (needs symfony/console)
!!  
!!  Makefile:22: recipe for target 'cache-warmup' failed
!!  
!!  make: *** [cache-warmup] Error 1
!!  
!!  

Installation failed, reverting ./composer.json to its original content.

**Comment by fabpot** [comment]
Has been fixed already. Upgrade to the latest version of symfony/flex.

**Comment by TheNovel** [comment]
I use flex v1.0.30 and get same problem.

**Comment by kironet** [comment]
Same here

**Comment by kironet** [comment]
@TheNovel @fabpot Same here. Just tried to install SF4.
`composer create-project symfony/skeleton my-project
`

**Comment by jav-mc** [comment]
@fabpot I have the same issue, although my error message is slightly different:

`Executing script make cache-warmup
Executed script make cache-warmup  [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  make: *** No rule to make target `cache-warmup'.  Stop.
!!
!!`

**Comment by mycodeself** [comment]
Same here 

`Updating dependencies (including require-dev)
Package operations: 24 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.30): Downloading (100%)         
  - Installing psr/log (1.0.2): Downloading (100%)         
  - Installing symfony/debug (v3.3.10): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.6.0): Downloading (100%)         
  - Installing symfony/console (v3.3.10): Downloading (100%)         
  - Installing symfony/stopwatch (v3.3.10): Downloading (100%)         
  - Installing symfony/routing (v3.3.10): Downloading (100%)         
  - Installing symfony/http-foundation (v3.3.10): Downloading (100%)         
  - Installing symfony/event-dispatcher (v3.3.10): Downloading (100%)         
  - Installing symfony/http-kernel (v3.3.10): Downloading (100%)         
  - Installing symfony/finder (v3.3.10): Downloading (100%)         
  - Installing symfony/filesystem (v3.3.10): Downloading (100%)         
  - Installing psr/container (1.0.0): Downloading (100%)         
  - Installing symfony/dependency-injection (v3.3.10): Downloading (100%)         
  - Installing symfony/config (v3.3.10): Downloading (100%)         
  - Installing symfony/class-loader (v3.3.10): Downloading (100%)         
  - Installing symfony/polyfill-apcu (v1.6.0): Downloading (100%)         
  - Installing psr/simple-cache (1.0.0): Downloading (100%)         
  - Installing psr/cache (1.0.1): Downloading (100%)         
  - Installing symfony/cache (v3.3.10): Downloading (100%)         
  - Installing doctrine/cache (v1.7.1): Downloading (100%)         
  - Installing symfony/framework-bundle (v3.3.10): Downloading (100%)         
  - Installing symfony/yaml (v3.3.10): Downloading (100%)         
  - Installing symfony/dotenv (v3.3.10): Downloading (100%)         
Writing lock file
Generating autoload files
Symfony operations: 4 recipes
  - Configuring symfony/flex (1.0): From github.com/symfony/recipes:master
  - Configuring symfony/console (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/routing (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/framework-bundle (3.3): From github.com/symfony/recipes:master
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  make: *** No rule to make target 'cache-warmup'.  Stop.
!!  
!!  
`

**Comment by samoilenko** [comment]
+1

```
Installing symfony/skeleton (v3.3.5)
  - Installing symfony/skeleton (v3.3.5): Downloading (100%)
Created project in api
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 24 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.30): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.3.10): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing symfony/console (v3.3.10): Loading from cache
  - Installing symfony/stopwatch (v3.3.10): Loading from cache
  - Installing symfony/routing (v3.3.10): Loading from cache
  - Installing symfony/http-foundation (v3.3.10): Loading from cache
  - Installing symfony/event-dispatcher (v3.3.10): Loading from cache
  - Installing symfony/http-kernel (v3.3.10): Loading from cache
  - Installing symfony/finder (v3.3.10): Loading from cache
  - Installing symfony/filesystem (v3.3.10): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v3.3.10): Loading from cache
  - Installing symfony/config (v3.3.10): Loading from cache
  - Installing symfony/class-loader (v3.3.10): Loading from cache
  - Installing symfony/polyfill-apcu (v1.6.0): Loading from cache
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v3.3.10): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing symfony/framework-bundle (v3.3.10): Loading from cache
  - Installing symfony/yaml (v3.3.10): Loading from cache
  - Installing symfony/dotenv (v3.3.10): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 4 recipes
  - Configuring symfony/flex (1.0): From github.com/symfony/recipes:master
  - Configuring symfony/console (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/routing (3.3): From github.com/symfony/recipes:master
  - Configuring symfony/framework-bundle (3.3): From github.com/symfony/recipes:master
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  make: *** No rule to make target 'cache-warmup'.  Stop.
!!
!!
```

**Comment by mycodeself** [comment]
I solve my problem adding a Makefile in root of project:

```
ifndef APP_ENV
	include .env
endif

.DEFAULT_GOAL := help
.PHONY: help
help:
	@grep -E '^[a-zA-Z-]+:.*?## .*$$' Makefile | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "[32m%-15s[0m %s\n", $$1, $$2}'

###> symfony/framework-bundle ###
CONSOLE := $(shell which bin/console)
sf_console:
ifndef CONSOLE
	@printf "Run \033[32mcomposer require cli\033[39m to install the Symfony console.\n"
endif

cache-clear: ## Clears the cache
ifdef CONSOLE
	@bin/console cache:clear --no-warmup
else
	@rm -rf var/cache/*
endif
.PHONY: cache-clear

cache-warmup: cache-clear ## Warms up an empty cache
ifdef CONSOLE
	@bin/console cache:warmup
else
	@printf "Cannot warm up the cache (needs symfony/console).\n"
endif
.PHONY: cache-warmup

serve_as_sf: sf_console
ifndef CONSOLE
	@${MAKE} serve_as_php
endif
	@bin/console list | grep server:start > /dev/null || ${MAKE} serve_as_php
	@bin/console server:start

	@printf "Quit the server with \033[32;49mbin/console server:stop\033[39m\n"

serve_as_php:
	@printf "\033[32;49mServer listening on http://127.0.0.1:8000\033[39m\n"
	@printf "Quit the server with CTRL-C.\n"
	@printf "Run \033[32mcomposer require symfony/web-server-bundle\033[39m for a better web server.\n"
	php -S 127.0.0.1:8000 -t public

serve: ## Runs a local web server
	@${MAKE} serve_as_sf
.PHONY: sf_console serve serve_as_sf serve_as_php
###< symfony/framework-bundle ###
```

**Comment by jav-mc** [comment]
@mycodeself as far as I understand, the error is because they're removing the make files, so your fix is going a step back.

**Comment by mycodeself** [comment]
Oh, I did not know that. How do you know it will not be used anymore?

Thanks

**Comment by Pierstoval** [comment]
@mycodeself You can check on fabpot's twitter: https://twitter.com/fabpot
Some polls were made about the makefile, and it has been decided to remove it in favor of `symfony/console` :wink: 

You should wait a little until every recipe is updated

**Comment by kironet** [comment]
Just remove:
` "make cache-warmup": "script",
`

from composer.json to prevent it from throwing error.

**Comment by fabpot** [comment]
fixed now
