### ISSUE TITLE
The composer.json file is not valid

### ISSUE THREAD

**Issue by lyrixx** [symfony/skeleton#171]
IMHO, we should put real constraint on theses requirements

```
require.symfony/console : unbound version constraints (*) should be avoided
require.symfony/dotenv : unbound version constraints (*) should be avoided
require.symfony/framework-bundle : unbound version constraints (*) should be avoided
require.symfony/yaml : unbound version constraints (*) should be avoided
```

**Comment by nicolas-grekas** [comment]
Already handled by flex, see https://github.com/symfony/flex/pull/435

**Comment by lyrixx** [comment]
IIUC, flex change this value during the computation. But the value is still here in the file. so `composer validate` continue to rant. Could we fix this?

**Comment by nicolas-grekas** [comment]
I don't understand what you mean:
```
composer create-project symfony/skeleton sftest
cd sftest
composer validate
```

yields no issues.

**Comment by lyrixx** [comment]
Indeed. I guess I have something strange in my app.

Thanks.
