### ISSUE TITLE
How to create older version project?

### ISSUE THREAD

**Issue by pcarew** [symfony/skeleton#181]
The oldest version available in https://packagist.org/packages/symfony/skeleton is v3.3.9

How do I create a project based upon 3.1?

"symfony new symf-test --version=3.1" fails with
 [InvalidArgumentException]
  Could not find package symfony/skeleton with version 3.1.*.

**Comment by nicolas-grekas** [comment]
You cannot: 3.1 is too old and is unsupported. Use 3.4 minimum now.
