### ISSUE TITLE
Question regarding the LICENSE added in version 5.1

### ISSUE THREAD

**Issue by ghost** [symfony/skeleton#187]
Hi, 

before v5.1 there was no LICENSE at the root of the folder that is now a part every new Symfony project. Does the application code have to be released under the same license, can the root license be modified to exclude the application code? Removed?

**Comment by fabpot** [comment]
There should be no LICENSE file whatever the version. Can you tell me when you have such a LICENSE file?

**Comment by ghost** [comment]
When runing any one of these:
composer create-project symfony/skeleton my_project_name
composer create-project symfony/website-skeleton my_project_name
symfony new my_project_name 
symfony new my_project_name --full

I presumed it was because the [license](https://github.com/symfony/skeleton/blob/master/LICENSE) is in this repository and it gets downloaded automatically. It isn't on the v5.0 branch or any previous one.

**Comment by ghost** [comment]
Using "_symfony new my_project_name --version=5.0_" does not include it

**Comment by ghost** [comment]
@fabpot  I'm just tagging you in case you missed the message.

**Comment by fabpot** [comment]
I see now that a LICENCE has been added. I will remove it. Just to be clear, the app you develop can have any license, no license, or just be a proprietary app.

**Comment by nicolas-grekas** [comment]
Removing the file is a job for flex, isn't it?

**Comment by ghost** [comment]
@fabpot Thank you for the clarification.

**Comment by fabpot** [comment]
See https://github.com/symfony/flex/pull/670 for the fix.
