### ISSUE TITLE
Symfony installer for 3.4 is broken

### ISSUE THREAD

**Issue by l-vo** [symfony/skeleton#189]
Hello,

there was a mistake on the `3.4.99` tag. The `3.4` branch is ok but the `3.4.99` tag targets the `5.2` version. Therefore `symfony new` and `composer create-project` with `3.4` version both create a project on Symfony `5.2`.

Regards.

**Comment by fabpot** [comment]
Fixed.

**Comment by kevin-verschaeve** [comment]
Hello,

It seems that this issue is reappeared.
Runnning `symfony new my_project --version=4.0` (which runs `composer create-project symfony/skeleton my_project 4.0.*`) creates a Symfony 5.1 project

**Comment by fabpot** [comment]
Indeed, /cc @nicolas-grekas

**Comment by nicolas-grekas** [comment]
https://flex.symfony.com/versions.json is missing entries for 4.0, that's why.

**Comment by fabpot** [comment]
Fixed

**Comment by nicolas-grekas** [comment]
Note that 4.0 is not maintained anymore, you should use 5.1 or 4.4 instead.

**Comment by kevin-verschaeve** [comment]
Yes, but it was for a training :D thanks for fixing it
