### ISSUE TITLE
Question: Where can I find the code that is copied into the target when creating a project based on this skeleton?

### ISSUE THREAD

**Issue by localheinz** [symfony/skeleton#190]
When running

```
 $ composer create-project symfony/skeleton
```

a whole lot of code (other than the contents of the `vendor/` directory) is copied into the target directory.

Where can I find that code on GitHub?

**Comment by xabbuh** [comment]
I guess what you are looking for are the [recipes](https://github.com/symfony/recipes) that are applied by Symfony Flex (see also https://symfony.com/doc/current/setup.html#installing-packages).

**Comment by localheinz** [comment]
Thank you, @xabbuh!
