### ISSUE TITLE
Composer Install Fails

### ISSUE THREAD

**Issue by ChrisWesterfield** [symfony/skeleton#2]
Composer Install fails with this message

> [197.8MB/8.99s]
>   Problem 1
>     - The requested package symfony/flex could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
> [161.8MB/9.03s] Memory usage: 161.82MB (peak: 197.98MB), time: 9.03s

Command: composer.phar install -vvv --profile

**Comment by fabpot** [comment]
That's expected as `symfony/flex` is not available yet. I'm working as fast as possible to publish it ASAP. Thanks for your patience.

**Comment by bluemanos** [comment]
@fabpot the Flex will be released at the same time with SF4 or earlier?

**Comment by TomasVotruba** [comment]
@bluemanos I think ASAP means somewhere between, but not sure where exactly.
As least from my experience with my open-source package release plans :)

**Comment by fabpot** [comment]
Most probably by the end of the month
