### ISSUE TITLE
Is preferred-install config still relevant?

### ISSUE THREAD

**Issue by MatTheCat** [symfony/skeleton#205]
[It apparently defaults to `dist`](https://getcomposer.org/doc/06-config.md#preferred-install).

Is it a discoverability thing or is it redundant?

**Comment by lyrixx** [comment]
Indeed. Would you mind to submit a PR?

**Comment by MatTheCat** [comment]
No problem :+1: 

Also it seems `composer/package-versions-deprecated` is not installed with the current skeleton; should it still appear in `allow-plugins`?

**Comment by nicolas-grekas** [comment]
Yes, the plugin list is on purpose. We trust them all, that's what this means.
