### ISSUE TITLE
Add cli to skeleton

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/skeleton#21]
I know, that this should be minimal. But I also think the cli should be required, cause:

- `make cache-warmup` lies on each following `composer req`
- `make serve` won't work as described in notes after install

I personally do a `create-project` and `composer req cli` on each test-project i currently install.

**Comment by fabpot** [comment]
Indeed, that won't happen. Regarding issues, I'm not sure what you are referring to, both make commands work fine for me. It there are problems, we should fix them instead.
