### ISSUE TITLE
skeleton script should not use `make cache:warmup`

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/skeleton#22]
As the cli (or symfony/console) is not available in skeleton app #21 the composer script:
```json
        "auto-scripts": {
            "make cache-warmup": "script",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
```
schould not call `make cache-warmup` as the console component isn't avaialble without doing `composer req cli`. 

This is what i ment with "`make cache:warmup` lies" in #21 Installing a broken package with or without cli available makes a big difference then. `make cache-warmup` is silent without cli and throws an error with cli.

So the script should not use the make command as the cli isn't available, but the function of doing a cache:warmup` should stay.

**Comment by fabpot** [comment]
Closing as Makefiles are gone. `symfony/console` is now a requirement in the base skeleton.
