### ISSUE TITLE
Make cache:clear command not found

### ISSUE THREAD

**Issue by tontonjulien** [symfony/skeleton#23]
```
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  /bin/sh: 1: printf: %q: invalid directive
!!  
!!  make: 
!!  cache:clear: Command not found
!!  
!!  
!!  make: *** [cache-clear] Error 127
!!  
!!  
```

**Comment by fabpot** [comment]
Can you tell us which OS you have?

**Comment by tontonjulien** [comment]
@fabpot Sure, I'm running Ubuntu 14.04 and GNU Make 3.81

**Comment by ElectricMaxxx** [comment]
Same here
* Ubunut 16.04
* PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 
* GNU Make 4.1
And here masive: https://travis-ci.org/symfony-cmf/install-testing

**Comment by ElectricMaxxx** [comment]
https://github.com/symfony/recipes/commit/34dc47b3be352ff7dc8b215099b5f4431ec17552 that chang, right? Shall i try locally to get the conditions working?

**Comment by fabpot** [comment]
fixed now

**Comment by tontonjulien** [comment]
thx @ElectricMaxxx
