### ISSUE TITLE
Flex dependency in require-dev section?

### ISSUE THREAD

**Issue by hhamon** [symfony/skeleton#24]
Hi,

After a very short discussion with @nicolas-grekas, I'm wondering if keeping the `symfony/flex`  dependency under the `require:` section of `composer.json` makes sense. Would it make more sense to have it under the `require-dev:` section instead. It seems that Flex is more like a dev tool only and I don't think the whole package needs to be deployed to production. I'm not sure about this and don't have much experience with it yet to make this assumption and this is why I'm asking for your advices.

Cheers.

**Comment by BoShurik** [comment]
Also `symfony/debug-pack` must be installed in `require` section because of `symfony/monolog-bundle` must be installed in all environments

**Comment by 20uf** [comment]
Hello,

I agree with your opinions, in my case, it serves only on the local environment (development).

**Comment by Pierstoval** [comment]
I also agree for flex as a dev dependency :+1:

**Comment by fabpot** [comment]
Done
