### ISSUE TITLE
Recipes do not run if composer.lock is present

### ISSUE THREAD

**Issue by dant89** [symfony/skeleton#25]
I added `"symfony/console": "^3.3"` to the default `composer.json`, changed my bin location using: `"config": {"bin-dir": "bin"}` and then ran `composer install`.

Success, everything installed correctly in the expected places, the recipes ran and the `console` symlink was created for my custom bin directory.

I committed both `composer` files to an empty repository and tried the same `composer install` with Jenkins on an empty workspace.

It installed the vendor files as expected but as there is a `composer.lock` present the Symfony **recipes are not executed** and the `console` file symlink to my custom bin location is not generated.

This means `composer install` fails because `bin/console` is not accessible as it erroneously hasn't been created due to `composer.lock` existing??

```
[exec]   - Installing squizlabs/php_codesniffer (2.9.1): Loading from cache
[exec]   - Installing symfony/dotenv (v3.3.10): Loading from cache
[exec]   - Installing symfony/phpunit-bridge (v3.3.10): Loading from cache
[exec] Generating autoload files
[exec] Executing script make cache-warmup [OK]
[exec] Executing script assets:install --symlink --relative public [KO]
[exec]  [KO]
[exec] Script assets:install --symlink --relative %PUBLIC_DIR% returned with error code 1
[exec] !!  Could not open input file: bin/console
```

Is this expected behaviour?

**Comment by Pierstoval** [comment]
Yes, recipes are only installed when using `composer require`, so updating your `composer.json file` will not trigger Flex because you'll have to run only `composer install` or `composer update`, which do not trigger Flex.

**Comment by dant89** [comment]
But surely the `console` file should be moved to the desired `bin` folder regardless of whether or not you're using `composer require`?

**Comment by fabpot** [comment]
If you modify your `composer.json` file manually, Flex will run. But only if Composer decides that the dependency is new... which does not seem to be the case here. The `bin/console` file must be committed to your repository.
