### ISSUE TITLE
composer install --no-dev fails

### ISSUE THREAD

**Issue by BPScott** [symfony/skeleton#32]
When prepping my application for deployment I want to run `composer install --no-dev` to remove any development only packages. Unfortunately this does not currently work with Flex, as the cache clear post-install step can not run.

You can reproduce this issue by cloning this repo and running `composer install --no-dev` or by running `composer create-project -s beta --no-dev symfony/skeleton:4.0.x sometestfolder`.

I get the error:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Dotenv\Dotenv' not found in /Users/bens92/projects/newtest/bin/console:19
```

This is because dotenv is currently marked as a development dependency, however in the [console recipe](https://github.com/symfony/recipes/blob/a371651216334324da6bc919b8cd2e2079491dfd/symfony/console/3.3/bin/console#L18-L20) the created console does not check for the existence of the DotEnv class before trying to use it.

---

There are two potential fixes to this, and I would like some guidance regarding which is preferential:

* Move dotenv into the main require block (from require-dev) in this repo
* Wrapping [all references to dotenv in the recipes repo](https://github.com/symfony/recipes/search?utf8=%E2%9C%93&q=Dotenv&type=) with a `class_exists()` check.

**Comment by votemike** [comment]
I believe that wrapping the calls in a `class_exists()` would be the better of the two options.

**Comment by wenmingtang** [comment]
pls remove `--no-dev` option after retry.

**Comment by fabpot** [comment]
For prod, env vars must be defined. If that's the case, the Dotenv part of the code is never run, and there is no issues. Am I missing something here?

**Comment by BPScott** [comment]
@fabpot this isn't quite in production, this is in a CI build job when creating up the code artefact that will then get deployed to production.

`APP_ENV=prod composer install --no-dev` works as expected, but this feels a little frail as this isn't the final deployment location. 

As you've confirmed that Dotenv is never ran in prod then it sounds like it certainly shouldn't be added in require, thanks.

I think a more useful error message might be useful though. What do you think to changing https://github.com/symfony/recipes/blob/56acc9cfb918c054ad56a44bafa40c953c130a3a/symfony/console/3.3/bin/console#L18-L20 from:

```php
if (!isset($_SERVER['APP_ENV'])) {
    (new Dotenv())->load(__DIR__.'/../.env');
}
```

to something like:

```php
if (!isset($_SERVER['APP_ENV'])) {
    if (!class_exists(Dotenv::class)) {
        throw new \RuntimeException('You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency');
    }
    (new Dotenv())->load(__DIR__.'/../.env');
}
```

**Comment by Pierstoval** [comment]
If it's a CI job, you should be able to provide all necessary env vars via its configuration. Travis-CI, CircleCI and possibly all other CI integrations allow adding environment vars for a job 🤔 

`Dotenv` [is already a dev dependency](https://github.com/symfony/skeleton/blob/master/composer.json#L16) in the default Symfony 4 project skeleton, because this component shouldn't be used in prod.

The real issue here is that you do not provide env vars, not that Dotenv is not enabled in production.

Nothing prevents you to create an `.env.ci` file in your project and run `cp .env.ci .env` or `source .env.ci` while executing your job, even though using native env vars injection should be a better solution 😕

**Comment by BPScott** [comment]
As noted, this is the wrong repo for this discussion, as Dotenv should indeed be a dev dependency.

Closing in favour of https://github.com/symfony/recipes/pull/247

**Comment by DIOHz0r** [comment]
Hello, I'm having this same error with a personal console project (https://github.com/DIOHz0r/cryptotrader) using ```composer install --no-dev ``` for distribution or production. 

You mention to include the .env file but it's ignored with .gitignore for be under control version and also it's created if I run the ```composer install --no-dev ``` but it throws the 255 error

![image](https://user-images.githubusercontent.com/1426313/44701103-f5a7e600-aa5a-11e8-87f8-67f34e84dca7.png)
