### ISSUE TITLE
 Could not find package symfony/skeleton with version 4.0.0-BETA2.

### ISSUE THREAD

**Issue by wenmingtang** [symfony/skeleton#33]
`composer create-project symfony/skeleton my-project-dir 4.0.0-BETA2`

[InvalidArgumentException]
Could not find package symfony/skeleton with version 4.0.0-BETA2.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by fabpot** [comment]
Try `composer create-project -s beta symfony/skeleton my-project-dir`

**Comment by wenmingtang** [comment]
@fabpot Thanks for your help.

**Comment by wenmingtang** [comment]
Hi, @fabpot 
This command can't install `Symfony-4.0.0-RC1` version.
`composer create-project -s RC symfony/skeleton my-project-dir`

I need your help.
Thanks.

**Comment by nicolas-grekas** [comment]
Try -s beta instead.

**Comment by fabpot** [comment]
@nicolas-grekas is right. But I've just published RC1 for both 3.4 and 4.0 so your command should work as well now.

**Comment by wenmingtang** [comment]
@fabpot 
It's ok now, Thanks.

**Comment by leparfait** [comment]
thank for your help

**Comment by SanijaPrakash** [comment]
[InvalidArgumentException]                                     
  Could not find package symfony/skelton with stability stable.

**Comment by xabbuh** [comment]
You have a typo in the package name (it's `symfony/skeleton`, not `symfony/skelton`).

**Comment by SanijaPrakash** [comment]
@xabbuh thanks a lot

**Comment by ahmed98** [comment]
in environnement variables change path **C://.../php/php5** with **C://...../php/php7.1.***

**Comment by yannred** [comment]
I had the same probleme with the command :

**Comment by farzam-raoufi** [comment]
composer create-project symfony/website-skeleton:"^4.4.*"  my_project_name

use * 
it helped me

**Comment by goncaloperes** [comment]
Specifying the version and running on CMD or Git Bash did the work for me.

See my answer [here](https://stackoverflow.com/a/73933626/7109869) where I share a few notes on the process.
