### ISSUE TITLE
Cannot create a Symfony 4 Project

### ISSUE THREAD

**Issue by benplummer** [symfony/skeleton#35]
Running `composer create-project symfony/skeleton my_project "4.0.*" -s dev` produces the following:

Installing symfony/skeleton (4.0.x-dev 592f0dae3ce846fbe9a612a4cf86336f49687ab6)
  - Installing symfony/skeleton (4.0.x-dev 592f0da)
    Cloning 592f0dae3ce846fbe9a612a4cf86336f49687ab6

Created project in my_project
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/flex v1.0.9 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.8 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.7 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.6 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.5 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.41 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.40 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.4 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.39 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.38 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.37 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.36 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.35 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.34 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.33 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.32 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.31 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.30 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.3 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.29 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.28 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.27 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.26 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.25 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.24 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.23 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.22 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.21 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.20 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.2 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.19 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.18 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.17 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.16 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.15 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.14 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.13 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.12 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.11 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.10 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.1 requires composer-plugin-api ^1.1 -> no matching package found.
    - symfony/flex v1.0.0 requires composer-plugin-api ^1.1 -> no matching package found.
    - Installation request for symfony/flex ^1.0 -> satisfiable by symfony/flex[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.17, v1.0.18, v1.0.19, v1.0.2, v1.0.20, v1.0.21, v1.0.22, v1.0.23, v1.0.24, v1.0.25, v1.0.26, v1.0.27, v1.0.28, v1.0.29, v1.0.3, v1.0.30, v1.0.31, v1.0.32, v1.0.33, v1.0.34, v1.0.35, v1.0.36, v1.0.37, v1.0.38, v1.0.39, v1.0.4, v1.0.40, v1.0.41, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Not sure if this should be here or in the Flex repository?

Thanks!

**Comment by wenmingtang** [comment]
Try `composer create-project -s RC symfony/skeleton my_project`

**Comment by nicolas-grekas** [comment]
That's because you're using an obsolete version of composer, try upgrading it from getcomposer.org

**Comment by benplummer** [comment]
Thanks, upgrading composer sorted it.
