### ISSUE TITLE
Pls release RC2 version

### ISSUE THREAD

**Issue by wenmingtang** [symfony/skeleton#36]
Thx.

**Comment by nicolas-grekas** [comment]
There is no need for RC2 (the skeleton versioning is independent from Symfony's)

**Comment by viion** [comment]
Hello, Didn't want to make a new post as it might be answerable here...

The current install via:
- `composer create-project symfony/skeleton my-project`

Installs version 3.3, which also installs `symfony/config 3.3`, however a lot of important packages require config 3.4 (eg Doctrine... Maker...), but Symfony `framework-bundle` requires 3.3

Will these be aligned/sorted in the SF4 release? The skeleton on this repo shows 3.4 config but that isn't the one that is used when you run the above command.

**Comment by nicolas-grekas** [comment]
composer create-project -s beta symfony/skeleton my-project

Should do it for now. Unrelated to the version of the skeleton.

**Comment by viion** [comment]
Would this not be an issue tomorrow if all repos move to stable? 

The documentation doesn't say that `beta` is required, and thus if you follow it you get a ton of versioning errors in composer.

Another work around is `minimum-stability: RC`

**Comment by nicolas-grekas** [comment]
That's the big party of tomorrow: tagging a bunch of repositories together yes :)

**Comment by Pierstoval** [comment]
Just wait until 3.4 is released in a few hours :wink:
