### ISSUE TITLE
dotenv not loading varibales

### ISSUE THREAD

**Issue by PhPPgAdminBug** [symfony/skeleton#37]
env
```
`# DB connection settings
DB_DRIVER=pgsql
DB_HOST=localhost
DB_PORT=5432
DB_NAME=test
DB_USER=homestead
DB_PASS=secret
```
`

yaml
```
`doctrine:
    dbal:
        driver:    '%env(DB_DRIVER)%'
        host:      '%env(DB_HOST)%'
        port:      '%env(DB_PORT)%'
        dbname:    '%env(DB_NAME)%'
        user:      '%env(DB_USER)%'
        password:  '%env(DB_PASS)%'
        charset: UTF8`
```

Clear install of skeleton.

**ERROR**
``Environment variable not found: "DB_DRIVER".
``

and all other too.

used docs
https://symfony.com/doc/current/configuration/external_parameters.html

**Comment by hacfi** [comment]
Did you install dotenv?

**Comment by nicolas-grekas** [comment]
Configuring Doctrine is not trivial due to the need for the server version at compile time.
Instead of doing the config yourself, I suggest to start with the provided one:
https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
