### ISSUE TITLE
symfony/web-server-bundle v4.0.0 conflicts with symfony/lts[v3]

### ISSUE THREAD

**Issue by zhang6longfei** [symfony/skeleton#38]
![image](https://user-images.githubusercontent.com/33275927/33534530-cf0c73fc-d8e2-11e7-8460-2e8e5b625f6e.png)

**Comment by Pierstoval** [comment]
Just require the 3.0 version: `composer req web-server-bundle:^3.0`

**Comment by nicolas-grekas** [comment]
@Pierstoval is correct
yet, that's what I would consider a bug in composer: not being able to take existing constraints into account when computing a default version constraint

**Comment by Pierstoval** [comment]
Isn't this a Flex issue when it resolves the package name?

**Comment by nicolas-grekas** [comment]
Flex resolves the name, composer resolves the version (when none is provided)

**Comment by Pierstoval** [comment]
Ok, then it's definitely a Composer issue 👍

**Comment by zhang6longfei** [comment]
@Pierstoval You are right.
