### ISSUE TITLE
/tests folder not created

### ISSUE THREAD

**Issue by lferro9000** [symfony/skeleton#39]
When creating a new skeleton app as stated by the docs in:

https://symfony.com/doc/current/setup.html

The project is created fine, however, when looking at composer.json file, the tests folder is defined in the autoload-dev, but the folder is not created in the project structure.

**Comment by lyrixx** [comment]
Hello.

You need to require the `phpunit` package in order to run your tests and also to create the `tests` folder:

    composer req phpunit

**Comment by fabpot** [comment]
@lyrixx is right.
