### ISSUE TITLE
Malformed parameter "url".

### ISSUE THREAD

**Issue by sjkoning** [symfony/skeleton#40]
I've just created my first Symfony 4 project. I've installed doctrine as well. I'm trying to set a connection to create my database and tables.

When I'm running `php bin/console doctrine:database:create` I get the error 

> In DriverManager.php line 259: Malformed parameter "url".

I don't understand. I've set the DATABASE_URL env variable inside .env: `DATABASE_URL="mysql://jack:jejW7!1Vo#ApE0D.dyR@127.0.0.1:3306/test"`

I have also set the fallback parameter inside doctrine.yaml: `env(DATABASE_URL): "mysql://jack:jejW7!1Vo#ApE0D.dyR@127.0.0.1:3306/test"`

I've tried removing the 'resolve:' prefix in the url (`url: '%env(resolve:DATABASE_URL)%'`) as well, but no luck.

Who can please help me out? What am I doing wrong? Any help will be appreciated a lot.

**Comment by Pierstoval** [comment]
It is the `#` sign that is not recognized by PHP's `parse_url()` function as valid

**Comment by curry684** [comment]
This is also definitely not an issue with `symfony/skeleton`.

**Comment by sjkoning** [comment]
By removing the `#` indeed fixed it for me. Thanks. My apologies for asking it here, however I had no problems whatsoever with the `#` in my password in Symfony 3.3.

**Comment by lyrixx** [comment]
for anyone reaching this issue: you need to `urlencode` the password to make it work ;)

**Comment by sonu27** [comment]
After using urlencode I get `The parameter "21c2" must be defined.`

Any ideas, that don't involve me having a simple password

**Comment by lyrixx** [comment]
you should encode only the password.

**Comment by tomaszturkowski** [comment]
@lyrixx I'm having the same issues like author of this thread and @sonu27 after doing urlencode of example password:
```
ZZ?*?daWm
```
I'm getting:
```
ZZ%3F%2A%3FdaWm
```
Full database url param:
```
DATABASE_URL=mysql://test_user:%3F%2A%3FdaWm@127.0.0.1:3306/test_db
```
which drives me into error like:

> In srcDevDebugProjectContainer.php line 294:
> 
>   The parameter "3F" must be defined.

Any clue?

**Comment by sonu27** [comment]
Thanks man! I’ll try that.

**Comment by pezzz** [comment]
Hi guys,
I have the same issue. I've tried urlencode for password(there's '?' char) and it was replaced with '%3F'. Then I got issue with 

> The parameter "3F"  must be defined.

So I removed 'resolve: prefix' as described above. But when I tried to use database connection it returned:
> An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'test_user'@'localhost' (using password: YES) 

I spent an hour trying to understand why it happens, even replaced '?' with '#' in password - the same result. I tried to take a look where the connection is created and echo connection parameters. Password there was still encoded. Should I set any option for proper decoding my password back?

I use: 
- Mysql 5.7
- PHP 7.2
- SF 4

Thank you in advance!

**Comment by sonu27** [comment]
Use a password without special characters :(

**Comment by mhujer** [comment]
It should be enough to change quotes to apostrophes in `.env`:
```
DATABASE_URL='mysql://root:123$!#!456R@127.0.0.1:3306/test'
```

(see https://github.com/symfony/symfony/issues/26056, and it has [already been changed in the Doctrine recipe](https://github.com/symfony/recipes/pull/361/files))

**Comment by pezzz** [comment]
Using apostrophes didn't help me so I decided to go deeper and found out the problem.
I checked my version of file `dbal/lib/Doctrine/DBAL/DriverManager.php` and didn't find any `urldecode()` [call](http://take.ms/EYGTH). So then I compared my file with version on github where I found  that there must be `rawurldecode` before `parseDatabaseUrlScheme`. 

The answer was simple - I had old version of doctrine/dba because composer used wrong PHP version on my server :( After setting up php version in composer/config/platform and updating, problem was fixed.

Thank you for help!

**Comment by curry684** [comment]
> I had old version of doctrine/dba because composer used wrong PHP version on my server :(

This implies you [did not commit your `composer.lock` file to version control](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control), which is incredibly important for exactly this reason.

**Comment by davidkmenta** [comment]
@tomaszturkowski hmmm... removing the "resolve:" prefix doesn't work for me :( it's necessary to escape the percent sign by doubling it "%%"...

**Comment by rachidbigm** [comment]
In my case i had a **#** in my password, and i just url encoded that char 💯

**Comment by mbrodala** [comment]
Newer issue: https://github.com/symfony/symfony/issues/35568

**Comment by coachaymen** [comment]
> #
If anyone is looking for a solution :
What solved my issue is to generate a new password.
