### ISSUE TITLE
line 13 in .env should be updated

### ISSUE THREAD

**Issue by TangMonk** [symfony/skeleton#41]
the url is wrong, should be `http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/`

**Comment by curry684** [comment]
Make a PR? :wink:

**Comment by lyrixx** [comment]
Why do think this URL is wrong?

for the reference, the .env is generated thanks to https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/manifest.json#L10

**Comment by fabpot** [comment]
Closing as this is the wrong repo. If the URL is wrong, can someone submit a pull request on symfony/recipes? Thank you.
