### ISSUE TITLE
Dependency conflict (symfony/lts 4.x-dev -> symfony/framework-bundle[dev-master])

### ISSUE THREAD

**Issue by carlosas** [symfony/skeleton#42]
The error is thrown just by running `composer install`:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for symfony/framework-bundle ^4.1 -> satisfiable by symfony/framework-bundle[4.1.x-dev].
>     - symfony/lts 4.x-dev conflicts with symfony/framework-bundle[dev-master].
>     - don't install symfony/framework-bundle 4.1.x-dev|install symfony/framework-bundle dev-master
>     - Installation request for symfony/lts ^4@dev -> satisfiable by symfony/lts[4.x-dev].
>

**Comment by nicolas-grekas** [comment]
Isn't this a composer issue?
See https://github.com/composer/composer/issues/6852

**Comment by fabpot** [comment]
@carlosas Without more information, it's very difficult to help you. There is either a real issue in your composer.json in terms of constraint, or perhaps have you hit the bug mentioned by @nicolas-grekas. Either way, nothing we can do.
