### ISSUE TITLE
Could not find package symfony/skeleton with version 3.4 in a version installable using your PHP version 5.6.32

### ISSUE THREAD

**Issue by yahuarkuntur** [symfony/skeleton#51]
```
$ composer create-project symfony/skeleton symfony34 3.4
                                                                                                                   
  [InvalidArgumentException]                                                                                        
  Could not find package symfony/skeleton with version 3.4 in a version installable using your PHP version 5.6.32.  
```

Composer version 1.5.6 2017-12-18 12:09:18
PHP 5.6.32-1+ubuntu14.04.1+deb.sury.org+2 (cli) 

Thanks!

**Comment by christiansiewert** [comment]
https://github.com/symfony/skeleton/blob/3.4/composer.json

```
"require": {
        "php": "^7.0.8",
```

**Comment by yahuarkuntur** [comment]
Symfony docs/site should be updated then:

https://symfony.com/doc/3.4/reference/requirements.html

```
Symfony 3.4 requires PHP 5.5.9 or higher to run, in addition to other minor requirements. To make things simple, Symfony provides a tool to quickly check if your system meets all those requirements.
```

**Comment by fabpot** [comment]
You can use Symfony 3.4 with PHP 5.5, but then, you need to use the Symfony Standard Edition. The PHP 7 requirement comes from Flex, not Symfony.

**Comment by yahuarkuntur** [comment]
Thanks! I am using the symfony installer for now and it's working:
````
$ symfony new symfony34 3.4
````

**Comment by itsazzad** [comment]
`composer create-project symfony/skeleton symfony34 3.4.99`

**Comment by vishnuvs369** [comment]
vishnu.vs@vishnu:/var/www/html$ composer create-project symfony/skeleton blog 

                                                                  
  [InvalidArgumentException]                                      
  Could not find package symfony/skeleton with stability stable.  
                                                                  

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by hacfi** [comment]
@vishnuvs369 What's your PHP and Composer version? Easiest if you copy and paste the results of `php -v` and `composer -V` here.

**Comment by hacfi** [comment]
@vishnuvs369 I think your Composer is very old..please try again after upgrading it.
