### ISSUE TITLE
No environment is loaded when APP_ENV is empty

### ISSUE THREAD

**Issue by codedmonkey** [symfony/skeleton#53]
This issue was first posted here https://github.com/symfony/symfony/issues/25711. To summarize,  under certain conditions, I ended up with a weird set of `$_SERVER` parameters ([see this comment](https://github.com/symfony/symfony/issues/25711#issuecomment-356153756)) and an empty string in `$_SERVER['APP_ENV']`, causing the debug bundle and profiler toolbar to unexpectedly not work.

I know it is a problem on my side that the `APP_ENV` changes it's value, but because it's an empty string, the following line of `public/index.php` of the default skeleton doesn't enable the development environment:

    $env = $_SERVER['APP_ENV'] ?? 'dev';

as `??` is not triggered when the initial value is an empty string.

I'm posting it here in case there's agreement that an empty environment string `!=` a valid environment.

**Comment by Pierstoval** [comment]
First, the workaround is simple:

```php
$env = isset($_SERVER['APP_ENV']) && $_SERVER['APP_ENV'] ? $_SERVER['APP_ENV'] : 'dev';
```

I know it sounds cumbersome, but you're saying that it's _"under certain conditions"_. At least this workaround will make things work for you like you expect.

**Comment by maxhelias** [comment]
Is this issue still relevant?
Or if you can close it, thank you

**Comment by fabpot** [comment]
I think this can be closed as it looks like something specific to the setup. As nobody else reported the same issue, the issue seems local.
