### ISSUE TITLE
[Question] ExpressionLanguage dependency

### ISSUE THREAD

**Issue by rogeriolino** [symfony/skeleton#54]
In a fresh symfony/skeleton install (composer create-project) after run `phpstan analyze` I'm getting the follow error:

```
------ ------------------------------------------------------------------------------------------------------ 
  Line   src/Kernel.php                                                                                        
 ------ ------------------------------------------------------------------------------------------------------ 
         Class Symfony\Component\ExpressionLanguage\ExpressionLanguage not found and could not be autoloaded.  
 ------ ------------------------------------------------------------------------------------------------------
```

App Kernel uses `DependencyInjection\ContainerBuilder`, ContainerBuilder has a property type of `Symfony\Component\DependencyInjection\ExpressionLanguage`. This **DI EL** extends `ExpressionLanguage\ExpressionLanguage`, but the `symfony/expression-language` package wasnt installed. The package `symfony/expression-language` is dev requirement of `symfony/dependency-injection`.

As `phpstan` is a step of my CI pipeline I've manually added `symfony/expression-language` to my application composer.json to prevent build errors.

Anyway, my question is:
Is `symfony/expression-language` really a dev dependency or this is a trouble with `phpstan` analysis?

```
composer create-project symfony/skeleton && cd skeleton
phpstan analyze -a vendor/autoload.php --level 1 src
```

**Comment by Pierstoval** [comment]
It's a dev dependency and it's not mandatory in the DI component. It's mostly to use expressions in your service definitions, like `service(your.service).callToAnyMethod()` as a service argument, for example.

**Comment by rogeriolino** [comment]
@Pierstoval I know it. The question is that exists a class in the dependency-injection package referencing explicitly (extends) a class from a dev dependency:

```
namespace Symfony\Component\DependencyInjection;

use Psr\Cache\CacheItemPoolInterface;
use Symfony\Component\ExpressionLanguage\ExpressionLanguage as BaseExpressionLanguage;

class ExpressionLanguage extends BaseExpressionLanguage
{
```

This doesnt throw any error because that referenced section is conditionally executed:

```
private function getExpressionLanguage()
    {
        if (null === $this->expressionLanguage) {
            if (!class_exists('Symfony\Component\ExpressionLanguage\ExpressionLanguage')) {
                throw new RuntimeException('Unable to use expressions as the Symfony ExpressionLanguage component is not installed.');
            }
            $this->expressionLanguage = new ExpressionLanguage(null, $this->expressionLanguageProviders);
        }

        return $this->expressionLanguage;
    }
```
But in a static analysis will raise error once the `BaseExpressionLanguage` not exists. Compilation error like in Java.

Should be a interface between the packages? Or just ignore it?

**Comment by Pierstoval** [comment]
Just ignore it, I find no advantage in adding another layer here. It's not Java here, it's an interpreted language, not a compiled one.

And by the way, I don't know why your static analysis would check the `vendor/` PHP files: you're not the one responsible of managing them. This update should be done on Github.

And finally, this is not a [symfony/skeleton](https://github.com/symfony/skeleton) issue, but more a [symfony/symfony](https://github.com/symfony/symfony) one.

**Comment by rogeriolino** [comment]
The analysis starts in **src/Kernel.php** (read the first message again).

I know what PHP is. Java is an example to clarify the question. I just think that you didnt understand my point.

By the way, this is a question, a debate, feel free to disagree/close the topic.

Regards.

**Comment by fabpot** [comment]
The way we manage deps in Symfony: we only list deps in `composer.json` that are needed for the core features. We never list optional deps like this is the case here. So, there is nothing to fix in Symfony. Is it a bug in phpstan? Probably not, just a false positive. You will get false positive with any tool that does static analysis in PHP (PHP is not Java :)).

**Comment by rogeriolino** [comment]
Hi @fabpot, thanks to reply. I agree with you in almost everything (just a detail).

> You will get false positive with any tool that does static analysis in PHP

But this statement is not true.

And sorry if it caused any inconvenience. I'm a heavy user of Symfony (and fan too) since v2, and PHP developer since non OOP era.

Regards.
