### ISSUE TITLE
Call to undefined method Composer\Json\JsonManipulator::addProperty()

### ISSUE THREAD

**Issue by zer0uno** [symfony/skeleton#55]
When I launch `composer create-project symfony/skeleton quick_tour` I get:

    PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Json\JsonManipulator::addProperty() in /home/antonio/Progetti/quick_tour/vendor/symfony/flex/src/Flex.php:557
    Stack trace:
    #0 /home/zer0uno/Progetti/quick_tour/vendor/symfony/flex/src/Flex.php(104): Symfony\Flex\Flex->getFlexId()
    #1 /usr/share/php/Composer/Plugin/PluginManager.php(215): Symfony\Flex\Flex->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
    #2 /usr/share/php/Composer/Plugin/PluginManager.php(188): Composer\Plugin\PluginManager->addPlugin(Object(Symfony\Flex\Flex))
    #3 /usr/share/php/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
    #4 /usr/share/php/Composer/Installer/InstallationManager.php(152): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
    #5 /usr/share/php/Composer/Installer/InstallationManager.php(139): Composer\Installer\InstallationManager in /home/antonio/Progetti/quick_tour/vendor/symfony/flex/src/Flex.php on line 557
    Fatal error: Uncaught Error: Call to undefined method Composer\Json\JsonManipulator::addProperty() in /home/zer0uno/Progetti/quick_tour/vendor/symfony/flex/src/Flex.php:557
    Stack trace:
    #0 /home/zer0uno/Progetti/quick_tour/vendor/symfony/flex/src/Flex.php(104): Symfony\Flex\Flex->getFlexId()
    #1 /usr/share/php/Composer/Plugin/PluginManager.php(215): Symfony\Flex\Flex->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
    #2 /usr/share/php/Composer/Plugin/PluginManager.php(188): Composer\Plugin\PluginManager->addPlugin(Object(Symfony\Flex\Flex))
    #3 /usr/share/php/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
    #4 /usr/share/php/Composer/Installer/InstallationManager.php(152): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
    #5 /usr/share/php/Composer/Installer/InstallationManager.php(139): Composer\Installer\InstallationManager in /home/zer0uno/Progetti/quick_tour/vendor/symfony/flex/src/Flex.php on line 557

**Comment by curry684** [comment]
Not reproducible with current stable and snapshot versions of Composer. Please ensure you are completely up to date by running `sudo composer self-update`.

**Comment by zer0uno** [comment]
Ok, the problem was my composer. I installed it via apt-get. Now, installing it via getcomposer.org, it works. Thank you.
