### ISSUE TITLE
A new git repository is initialized on composer install

### ISSUE THREAD

**Issue by pensiero** [symfony/skeleton#56]
I'm not sure about who's the fault, never happened with other `composer.json` configs: if I run `composer install` in a folder of a project (under git version control), it creates a new `.git` folder.

Is it something related to this skeleton, or I'm missing something?

Thanks

**Comment by Pierstoval** [comment]
It's related to the `symfony/flex` recipe: https://github.com/symfony/recipes/tree/master/symfony/flex/1.0/git

It creates a new git repository when creating the project.

**Comment by pensiero** [comment]
Do you think there's a chance to not trigger it, without removing flex?

**Comment by Pierstoval** [comment]
It's not possible to prevent a Flex recipe to be installed when Flex is enabled.

The only way to disable this default git repository is to create your project, keep your `symfony.lock` file, make sure it contains a `symfony/flex` instruction, and remove the git directory afterwards.

But even then, it's always a good practice to create a git repo of your project, so I don't see why it would be a problem?

**Comment by pensiero** [comment]
For this reason: https://github.com/pensiero/docker-skeletons/tree/master/symfony/4.0
:) It's the skeleton dockerized, but's it's part of a bigger repo.

**Comment by pensiero** [comment]
@maxhelias nope, I don't know if it solves... I could try, thanks

**Comment by fabpot** [comment]
Indeed, let's close this one as a duplicate.
