### ISSUE TITLE
Dependent Dev Package

### ISSUE THREAD

**Issue by godsgood33** [symfony/skeleton#57]
I'm really confused.  I'm trying to include symfony/skeleton with composer (^4.0), but I'm getting an error that the dependent symfony/lts is at v4@dev so it doesn't meet my minimum stability requirements.  Why is a dev package required?  And I can't figure out how to override that include.  Thanks!

**Comment by godsgood33** [comment]
If I load the packages listed in the required skeleton package, things work just fine.

**Comment by pensiero** [comment]
It happened the same to me, I'm interested in the topic :)

**Comment by godsgood33** [comment]
Starting a project from scratch works, but I want to add Symfony to my project instead of starting over and having to copy everything.

**Comment by pensiero** [comment]
@stuzzo take a look here: https://github.com/pensiero/docker-skeletons ;)

**Comment by fabpot** [comment]
You should not include `symfony/skeleton` as this package is just useful to create a new project (when using `composer create-project`, the `symfony/skeleton` package becomes the root, so it's not it the `composer.json`). If you are upgrading an existing project, then you need to add the dependencies directly.
