### ISSUE TITLE
error to create a symfony4 project

### ISSUE THREAD

**Issue by leparfait** [symfony/skeleton#59]
I am not able to create a symfony4 project in my computer i have this error:

 **[InvalidArgumentException]
  Could not find package symfony/skeleton with stability stable in a version installable using your PHP vers
  ion 5.6.25.**

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by JanGolle** [comment]
Sure, because this project requires PHP version 7.1.3 or above.

`"php": "^7.1.3"`

**Comment by nicolas-grekas** [comment]
Actually the skeleton supports also 7.0, using branch 3.4. But that wouldn't change the issue for you.
You can start with the standard edition instead: https://github.com/symfony/symfony-standard/
Or upgrade PHP (would be the best).

**Comment by leparfait** [comment]
thank you ,  it work

2018-02-18 15:50 GMT+01:00 Nicolas Grekas <notifications@github.com>:
