### ISSUE TITLE
Type coercion breaks null coalesce operator

### ISSUE THREAD

**Issue by polycodedev** [symfony/skeleton#60]
Hi,

I'm not sure if this is the right place to post this, but the default `index.php` file has a bug in it when using `composer create-project symfony/skeleton`.

Line 19:
```php
$debug = (bool) $_SERVER['APP_DEBUG'] ?? ('prod' !== $env);
```

The coercion of `$_SERVER['APP_DEBUG']` to type `bool` occurs before `??` and therefore throws an undefined index exception by default as it's not set.

It's easy enough to fix obviously, but from a usability standpoint it could be confusing for new Symfony users following the introductory tutorial. In the tutorial the project is created and then immediately served with `php -S 127.0.0.1:8000 -t public` which throws the exception when you visit the page.

**Comment by lyrixx** [comment]
Thanks @polycodedev for noticing this issue.
I have submitted a R to fix this issue.

**Comment by lyrixx** [comment]
@fabpot The PR has been merged. You can safely close this issue
