### ISSUE TITLE
Please stick to semver-compliant version numbers

### ISSUE THREAD

**Issue by teohhanhui** [symfony/skeleton#70]
`3.4.12.1`, `4.0.12.1` and `4.1.1.1` are not semver-compliant.

**Comment by fabpot** [comment]
metadata won't work for us as we need to have version precedence.

**Comment by nicolas-grekas** [comment]
The current versioning scheme works well in practice: version numbers have the correct precedence, and the first three numbers match the Symfony version that is targeted.
Do you have a better proposal? I don't personally.

**Comment by nicolas-grekas** [comment]
> the first three numbers match the Symfony version that is targeted.

Note that not doing so led to WTFs.
Since this package is not meant to be targeted as a dependency, it doesn't have to follow semver IMHO. It's version number is irrelevant after installation.

**Comment by teohhanhui** [comment]
> the first three numbers match the Symfony version that is targeted.

Fair point.
